name: Build

on:
  push:
    branches: master
  pull_request:
    branches: master
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      shell: bash
      run: |
         sudo apt update
         sudo apt install gcc-10
         sudo update-alternatives \
          --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 \
          --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-10 \
          --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-10 \
          --slave /usr/bin/gcov gcov /usr/bin/gcov-10
    - name: Compile
      shell: bash
      env:
        CC:   gcc-10
      run: |
        gcc --version
        gcc-10 --version
        if [ ! -d "./out" ]; then
          mkdir out
        fi
        make
    - name: Run Tests
      shell: bash
      run: ./out/test_renderer
