name: Build

on:
  push:
    branches: master
  pull_request:
    branches: master
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      shell: bash
      run: |
         sudo apt update
         sudo apt install gcc-10
         sudo update-alternatives \
          --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 \
          --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-10 \
          --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-10 \
          --slave /usr/bin/gcov gcov /usr/bin/gcov-10
    - name: Compile
      shell: bash
      run: |
        if [ ! -d "./out" ]; then
          mkdir out
        fi
        make
    - name: Run Tests
      shell: bash
      run: ./out/test_renderer
    - name: Codecov
      uses: codecov/codecov-action@v3.1.2
      with:
        gcov: true
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage1.xml,./coverage2.xml # optional
        flags: unittests # optional
        name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
