name: Build

on:
  push:
    branches: master
  pull_request:
    branches: master
  workflow_dispatch:

jobs:
  Build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Compile
      run: |
        env
        if [ ! -d "./out" ]; then
          mkdir out
        fi
        make
    - name: Run Tests
      run: ./out/test_renderer
