name: Build

on:
  push:
    branches: master
  pull_request:
    branches: master
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    
    - name: Compile Renderer
      shell: bash
      run: |
        if [ ! -d "./out" ]; then
          mkdir out
        fi
        make renderer
    
    - name: Compile Tests
      shell: bash
      run: make clean && make test
    
    - name: Run Tests
      shell: bash
      run: ./out/test_renderer
      
    - name: Run gcov
      shell: bash
      run: |
        for filename in `find ./src -not \( -path ./src/test -prune \) -name "*.c"`; 
        do 
          echo $filename
          gcov -pb -r -o ./out $filename
        done
        ls -la
    
    - name: Codecov
      uses: codecov/codecov-action@v3.1.2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./
        fail_ci_if_error: true
        verbose: true
