name: Build

on:
  push:
    branches: master
  pull_request:
    branches: master
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      shell: bash
      run: |
         sudo apt update
         sudo apt install gcc-10
    - name: Compile
      shell: bash
      env:
        CC:   gcc-10
      run: |
        if [ ! -d "./out" ]; then
          mkdir out
        fi
        make
    - name: Run Tests
      shell: bash
      run: ./out/test_renderer
